language: python
python: 2.7

install:
  - pip install -r test-requirements.txt
  - pip install coveralls
script:
  - py.test pynetlib --pep8 --cov=pynetlib --cov-report term-missing
after_success:
  - coveralls

sudo: false
